index:
    path: /
    controller: App\Controller\AppController::indexAction

live_feed:
    path: /live/jobs
    controller: App\Controller\LiveController::feedAction

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/resetting"

trackerCallback:
    path: /trackerCallback
    controller: App\Controller\TrackerCallback::callbackAction

profile:
    resource: routes_profile.yaml
    prefix: "/profile"
