index:
    path: /
    controller: App\Controller\HomeController::indexAction

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: "/profile"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/resetting"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/profile/security"

trackerCallback:
    path: /trackerCallback
    controller: App\Controller\TrackerCallback::callbackAction

profile:
    resource: routes_profile.yaml
    prefix: "/profile"
